namespace: nginx-node-test
replicaCount: 1

image:
  repository: tar3kom/nginx-node-test
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regcred-nginx-node-test

# envFrom:
#   configMaps:
#     - mnsp-genlink-portal
#   secrets:
#     - mnsp-genlink-portal

service:
  type: ClusterIP
  port: 80
  targetPort: 80
