namespace: nginx-node-test
replicaCount: 3

image:
  repository: docker.io/tar3kom/nginx-node-test
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regcred-nginx-node-test

# envFrom:
#   configMaps:
#     - mnsp-genlink-portal
#   secrets:
#     - mnsp-genlink-portal

service:
  type: ClusterIP
  port: 8061
  targetPort: 80
