namespace: nginx-node-test
replicaCount: 3

image:
  repository: https://github.com/tar3kom/nginx-node-test.git
  tag: 251106_2_korn
  pullPolicy: Always

imagePullSecrets:
  - name: regcred-nginx-node-test

# envFrom:
#   configMaps:
#     - mnsp-genlink-portal
#   secrets:
#     - mnsp-genlink-portal

service:
  type: ClusterIP
  port: 8061
  targetPort: 80
